version: "3"

services:
  pg:
    image: "index.docker.io/systeminit/postgres:stable"
    environment:
      - "POSTGRES_PASSWORD=bugbear"
      - "PGPASSWORD=bugbear"
      - "POSTGRES_USER=si"
      - "POSTGRES_DB=si"
      - "POSTGRES_MULTIPLE_DBS=si_test,si_test_dal,si_test_sdf_server,si_auth,si_module_index"
    ports:
      - "5432:5432"

  nats:
    image: "index.docker.io/systeminit/nats:stable"
    ports:
      - "4222:4222"
    command:
      - "--config"
      - "nats-server.conf"
      - "-DVV"

  jaeger:
    image: "index.docker.io/jaegertracing/all-in-one:1.43"
    ports:
      - "5317:4317"
      - "16686:16686"
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"

  otel:
    image: "index.docker.io/systeminit/otelcol:stable"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "4317:4317"
      - "55679:55679"
    depends_on:
      - jaeger
