---
name: bors
on:
  push:
    branches:
      - staging
      - trying

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 40
    name: Merge Request Checks
    runs-on: self-hosted
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install node dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login Docker
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: bors merge test
        id: bors-merge-test
        run: |
          : make ci
          source /data/runners/.profile
          make \
            CI=true \
            CI_FROM_REF=${{ github.event.before }} \
            CI_TO_REF=${{ github.event.after }} \
            SKIP_CHECK=true \
            ci
        env:
          HONEYCOMB_TOKEN: ${{ secrets.HONEYCOMB_TOKEN }}
          RUSTC_WRAPPER: /usr/local/bin/sccache
          CARGO_INCREMENTAL: false
